[project]
name = "download-blob-videos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.12.15",
    "black>=25.9.0",
    "rich>=14.1.0",
]
